#!/usr/bin/env python3
import os
import sys

HERE = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, os.path.abspath(HERE))

from savery import __main__  # noqa: E402, isort:skip

if __name__ == '__main__':
    __main__.main()
